### ISSUE TITLE
Obfuscation can not replace encryption.

### ISSUE THREAD

**Issue by nemozqqz** [clayface/openvpn_xorpatch#9]
DO NOT turn off OpenVPN's own encryption when using this  xorpatch or [this](https://github.com/siren1117/openvpn-obfuscation-release).
It is NOT ok to use ['cipher none'](https://forums.openvpn.net/viewtopic.php?f=15&t=12605&hilit=openvpn_xorpatch), which makes all traffic tunnel in plaintext.
Obfuscation can not replace encryption.

**Comment by clayface** [comment]
Added info to the readme to state this. Thanks
